### ISSUE TITLE
Performance regression with GHC 8.8

### ISSUE THREAD

**Issue by andrewthad** [layer-3-communications/pan-os-syslog#1]
When building d81a453ec4acbc519b84aa6b56aa1f903a36705b with GHC 8.6.5, the benchmark `8-1-Traffic-A` completes in 763ns. With GHC 8.8.1, this same benchmark takes 1138ns. Actually figuring out why this happen is probably a lengthy and non-worthwhile investment of time that would involve looking at the optimized Core of this library and of `bytesmith`. I don't plan on trying to do anything about this any time soon, but I'll leave this issue here as a reminder that something has regressed.

**Comment by AndreasPK** [comment]
This should be fixed come 8.10 which will contain my patches.

Benchmarks were done with music in the background but no heavy load so should be indicative of actual performance.

### 8.6.5

```
$ cabal new-run bench
benchmarking 8-1-Traffic-A ...
time                 677.6 ns   (631.9 ns .. 726.3 ns)

benchmarking 8-1-Threat-A ...
time                 768.6 ns   (712.9 ns .. 852.8 ns)

benchmarking 8-1-Threat-B ...
time                 803.0 ns   (758.1 ns .. 858.6 ns)

benchmarking 8-1-Threat-C ...
time                 697.0 ns   (653.8 ns .. 743.8 ns)
```

### 8.8 Performance - Noteable regression

```
$ cabal new-run bench -w /e/ghc-8.8.1/bin/ghc.exe
benchmarking 8-1-Traffic-A ...
time                 768.5 ns   (740.1 ns .. 808.8 ns)

benchmarking 8-1-Threat-A ...
time                 841.3 ns   (819.2 ns .. 861.5 ns)
benchmarking 8-1-Threat-B ...
time                 983.7 ns   (943.5 ns .. 1.039 us)
benchmarking 8-1-Threat-C ...
time                 815.5 ns   (790.1 ns .. 851.9 ns)
```


### Summer of performance patchset - Equal or better performance than 8.6.5 for all cases
```
Andi@Horzube MINGW64 /e/pan-os-syslog
$ cabal new-run bench -w /e/ghc_layout/_quick/stage1/bin/ghc.exe --allow-newer="*"
benchmarked 8-1-Traffic-A
time                 626.4 ns   (611.3 ns .. 647.4 ns)

benchmarking 8-1-Threat-A ...
time                 689.7 ns   (655.7 ns .. 722.5 ns)

benchmarking 8-1-Threat-B ...
time                 779.2 ns   (747.3 ns .. 815.3 ns)

benchmarking 8-1-Threat-C ...
time                 696.0 ns   (665.5 ns .. 742.6 ns)
```

**Comment by AndreasPK** [comment]
Given that the regression is gone with 8.10 I won't spend time investigating the reasons. But I always appreciate tickets on the ghc tracker about these kinds of regressions.

Especially when the benchmarks are as easy to run as it was in this case.

**Comment by andrewthad** [comment]
Awesome! That is wonderful news. I typically avoid opening issues on GHC when I cannot minimize them, but I'll start doing it for things like this in the future. I've had to write several of these low-allocation parsers lately that are amenable to microbenchmarking, so this may come up again in a different library.
